server:
  port: 8001
  max-http-header-size: 102400
  tomcat:
    remoteip:
      port-header: PUT,DELETE,OPTIONS,TRACE,PROPFIND,COPY,SEARCH
  servlet:
    context-path: /tas                        # 设置项目启动根路径
switchToStart: false
spring:
  datasource:
    url: jdbc:mysql://www.likeblue.cn:3306/tas_tmh?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Tmh625819
    type: com.alibaba.druid.pool.DruidDataSource #开启druid连接池
    druid:
      # 连接池基本配置
      initial-size: 5                           # 启动时创建的连接数量
      min-idle: 5                               # 池中保持空闲的最小连接数
      max-active: 20                            # 同一时间可从池中分配的最多连接数,如果设置为0,表示无限制
      max-wait: 60000                           # 抛出异常之前，池连接等待回收的最大时间,如果设置为-1,表示无限制
      min-evictable-idle-time-millis: 300000    # 连接池空闲连接的有效时间
      validation-query: SELECT 1 FROM test      # 测试连接语句
      time-between-eviction-runs-millis: 60000  # 空闲连接回收的时间间隔,与test-while-idle一起使用
      test-while-idle: true                     # 验证连接的有效性
      test-on-borrow: true                      # 获取连接时验证
      test-on-return: false                     # 在连接归还到连接池时是否测试该连接
      pool-prepared-statements: true            # 是否对预处理语句进行池管理
      default-auto-commit: true                 # 开启自动提交
      # 监控配置
      aop-patterns: org.blue.*                  # Spring监控AOP切入点
      filters: stat,wall,log4j2                 # 开启状态、防火墙、日志过滤
      stat-view-servlet:
        enabled: true                           # 开启网页SQL视图管理
        login-username: tian                    # 登录/druid的用户名
        login-password: 2019121218              # 密码
        reset-enable: true                      # 开启重置功能
      web-stat-filter:
        enabled: true                           # 开启防火墙过滤
        url-pattern: /*                         # 过滤根路径下所有
        exclusions: '*.js,*.gif,*.jpg,*.css,*.ico,/druid/*' # 过滤排除的内容
      filter:
        stat:
          log-slow-sql: true                    # 开启慢sql过滤
          slow-sql-millis: 1000                 # 设置慢sql执行时间
          enabled: true                         # 开启过滤
        slf4j:
          enabled: true                         # 开启sql日志
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
  servlet:
    multipart:
      max-file-size: 100MB                      # 配置文件上传最大大小
      max-request-size: 50MB                    # 配置网络最大请求大小

mybatis-plus:
  type-aliases-package: org.tian.tas.entity     # 配置mybatis-plus别名映射的包
  global-config:
    banner: false                               # 关闭条幅显示
  configuration:
    map-underscore-to-camel-case: true          # 开启驼峰映射
    call-setters-on-nulls: true                 # 结果可以为空
  mapper-locations:
    classpath*: /mapper/*.xml                   # mapper映射文件地址