server:
  port: 80
  max-http-header-size: 102400
  tomcat:
    remoteip:
      port-header: PUT,DELETE,OPTIONS,TRACE,PROPFIND,COPY,SEARCH
  servlet:
    context-path: /tas

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/tas?createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Tmh010625
    druid:
      default-auto-commit: true
      aop-patterns: org.blue.*
      filters: stat,wall,log4j2
      stat-view-servlet:
        enabled: true
        login-username: tian
        login-password: 2019121218
        reset-enable: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: '*.js,*.gif,*.jpg,*.css,*.ico,/druid/*'
      filter:
        stat:
          log-slow-sql: true
          slow-sql-millis: 1000
          enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

mybatis-plus:
  type-aliases-package: org.tian.tas.entity
  global-config:
    banner: false
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
  mapper-locations:
    classpath*: /mapper/*.xml